//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int RegistrationID { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public string CategoryOfRoom { get; set; }
        public int NumberOfRoom { get; set; }
        public int NumberOfPeople { get; set; }
        public System.DateTime DateOfRice { get; set; }
        public int StayPeriod { get; set; }
        public string Login { get; set; }
    }
}
