//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondOfNumbers
    {
        public FondOfNumbers()
        {
            this.Living = new HashSet<Living>();
            this.Places = new HashSet<Places>();
        }
    
        public int NumberOfRoom { get; set; }
        public string CategoryOfRoom { get; set; }
        public float Price { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Living> Living { get; set; }
        public virtual ICollection<Places> Places { get; set; }
    }
}
