//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Living
    {
        public int ID { get; set; }
        public System.DateTime DateOfRice { get; set; }
        public Nullable<System.DateTime> DateOfLeave { get; set; }
        public int NumberOfRoom { get; set; }
        public string Place { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Passport { get; set; }
    
        public virtual FondOfNumbers FondOfNumbers { get; set; }
    }
}
