//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities2 : DbContext
    {
        public hotelEntities2()
            : base("name=hotelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<FondOfNumbers> FondOfNumbers { get; set; }
        public virtual DbSet<Living> Living { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Remember> Remember { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
