//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int IDOfPlace { get; set; }
        public int NumberOfRoom { get; set; }
        public string Place { get; set; }
    
        public virtual FondOfNumbers FondOfNumbers { get; set; }
    }
}
